### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by WeebNetsu** [Drumber/Kitsune#1]
I have a list of a few features that are missing or would be nice to have in the app:

- Allow us to set the default tab the app opens up in (ie. I would like mine to open in the Library tab)
- Only update read/watch after a few seconds, currently whenever you update the current chapter/episode you're on you have to wait for it to update first before you can tap again, if you're someone like me who reads 10-20 chapters in one sitting, then updating one by one is very slow, so maybe wait 2-5 seconds after the last tap before saving the data?
- Allow 10 star reviews, currently when you review an anime/manga, you can only rate it out of 5, I would like to rate mine out of 10 (like how I do it on the Kitsu website)
- Split library between Mangas and Animes, so maybe have a tab that only has manga, and a tab that only has the anime you're watching

Other than these few things, I think the app is really awesome, and already way better then the official app! :)

**Comment by Drumber** [comment]
Hi, thanks for your suggestions!
I've also been thinking about some of your points as well, and I will probably look into those the next time I work on the app.
The rating system and library updates are one of the things I would definitely like to improve.

As of splitting the library between Manga and Anime, you can already do that with the filter below the app bar (it's set to `All` by default).

**Comment by Drumber** [comment]
It took a year, but in v1.8.0 you can finally make changes to the episode/chapter progress without having to wait after each tap.
