### ISSUE TITLE
Profile Picture instead of the generic profile icon

### ISSUE THREAD

**Issue by ShomyKohai** [Drumber/Kitsune#18]
I was thinking it would be good to have the user profile picture at the bottom right instead of the generic profile icon when logged in!

**Comment by Drumber** [comment]
Hi, thanks for your suggestion. I think that would be pretty cool! Similar to how it is in the GitHub Mobile app.

However, I was thinking of removing the profile menu icon from the bottom navigation bar altogether and instead adding a search bar with a trailing profile icon on the main pages, similar to what you see in most Google Apps.

I'll leave this issue open here and see what's feasible.

**Comment by ShomyKohai** [comment]
> similar to what you see in most Google Apps
Oh I get what you mean! 
I noticed though that the YouTube App moved the user icon from the top to the bottom like the GitHub App does, but i don't know they're just testing stuff or what!
In my opinion having it on the bottom right makes it more accessible instead of having to move the finger all to the top of the screen!

**Comment by Drumber** [comment]
Added in v1.9.1
