### ISSUE TITLE
Library Filter Multiple Selection

### ISSUE THREAD

**Issue by ShomyKohai** [Drumber/Kitsune#2]
I think I found a bug:
I can select multiple status as a filter for a media in the library; when I select multiple filters, it shows all the entries as no filter was applied

![Screenshot_20221007-125234~01.jpg](https://user-images.githubusercontent.com/61943525/194537537-e012a11b-1c0d-4cd4-a660-c3fa484e2705.jpg)

**Comment by Drumber** [comment]
Hi, it's actually not a bug. It's intended that you can select multiple filters. The reason for this is that someone may want to have only library entries of certain status types (e.g. 'Watching' and 'Want to watch') displayed.

However, it is true that selecting all filters has the same effect as when no filter is selected and I should possibly revise this.

**Comment by Drumber** [comment]
I made the filtering of the library more clear in the last version. Now the filters will be cleared, when you select all status filters. I also added separators between different statuses to make it more clear to what status type the displayed medias belongs.
