### ISSUE TITLE
Allow to upload profile picture and banner

### ISSUE THREAD

**Issue by ShomyKohai** [Drumber/Kitsune#21]
Currently I don't find a way to update my profile picture or banner from the app

**Comment by Drumber** [comment]
Hey, at the moment it's actually not possible to edit your profile (About me, profile picture, banner, etc) in Kitsune.
But I have already planned to add this feature when I have time.

Until then, you'll have to use the official app or the website to update your profile.

**Comment by Drumber** [comment]
Added in v1.10.0
