### ISSUE TITLE
Home Screen Widget

### ISSUE THREAD

**Issue by shomykohai** [Drumber/Kitsune#24]
It would be nice to have widgets for the homescreen to quickly update library entries
I imagined something like this (sorry for the low quality, i've made it quickly with ms paint)
![image](https://github.com/Drumber/Kitsune/assets/61943525/360c4ae3-672b-4f68-8e9d-1e398f800a84)

**Comment by Drumber** [comment]
Hi, thanks for the suggestion, that would definitely be a useful feature! I'll add this to the To Do list.
However, this can be a bit of work, as we may need to periodically synchronize the library in the background to display up-to-date data in the case that the library has been modified outside of Kitsune.

**Comment by Drumber** [comment]
I have finally found some time to work on this. The widget is now available in [v2.0.0](https://github.com/Drumber/Kitsune/releases/tag/v2.0.0). It shows the anime and manga that are currently being watched/read.
