### ISSUE TITLE
Add check for update in parentheses next to app version!! 

### ISSUE THREAD

**Issue by MarshMeadow** [Drumber/Kitsune#37]
Add ("check for update") in parentheses next to app version, please 🥺🥺🥺

**Comment by Drumber** [comment]
Haha, yeah I should make that more obvious. However, I would recommend having the "Check for Updates on Launch" option enabled anyway to get notified about new releases ^^

By the way, there are more of these "hidden actions". Like on most pages you can click on the selected menu item in the bottom navigation to scroll up, go back or focus the search bar.
And there are a few long-click actions, e.g. long-clicking on a library entry opens the details or long-clicking on the filter icon on the search page clears all selected filters.
I should at least document them somewhere 😅. I think they can be really useful, but people don't know about these actions.

**Comment by Drumber** [comment]
> Check for Updates on Launch??
> i though you had that???
> i have it on mine..

Yeah, I have that option. I just meant that if you have the option "Check for updates on Launch" turned on, you don't really need to manually check for updates.

**Comment by Drumber** [comment]
Added in v1.10.2
