### ISSUE TITLE
Add Average User Rating to TV/Movie pages

### ISSUE THREAD

**Issue by foohsaile** [Drumber/Kitsune#39]
could it be possible to display some sort of an "average user rating" on each anime's page? There already exists the "Ratings" section on the bottom of every page but even with that its a bit hard to really assess user's reception on a particular anime.

since the data for user ratings is already there, i imagine it shouldn't be too hard to implement

**Comment by Drumber** [comment]
Hi, the average rating is already displayed right at the top. It's called “Kitsu Score” ;)
It comes from the averageRating value returned by the Kitsu API.

![Screenshot 2024-05-06 164706](https://github.com/Drumber/Kitsune/assets/29163322/e19ea684-52b8-4f60-9cf0-4665019c5cd5)

**Comment by Drumber** [comment]
Ok, got it, That would be possible, just need to find a place where I can add it (maybe under the ratings diagram?).

**Comment by Drumber** [comment]
Added in v1.10.5
