### ISSUE TITLE
Add on-boarding on first launch

### ISSUE THREAD

**Issue by Drumber** [Drumber/Kitsune#52]
Add an on-boarding tour for new users.

- [x] Introduce the app and its features to the user.
- [x] Let the user log-in or register to Kitsu.io.
- [x] Let the user enable the update checker.

**Comment by ZineeEddine** [comment]
Hello @Drumber , I think we can work on this issue with @EragonRD , but we need more details regarding the tutorial and the layout, what design did you want.

Whether the tutorial is swipable, or clickable on the next button?

Should we display the little dots below each page?

How many tutorial pages should there be? 

For this application 4 pages seems correct to me


Here are some inspirations found on the internet :
<table>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/b0e98ddb-9a84-4107-8270-f772d720d03d" width="50%"></td>
    <td><img src="https://github.com/user-attachments/assets/88ca4997-96e8-4b02-b7e1-b800ad5c56e8" width="50%"></td>
  </tr>
</table>

**Comment by Drumber** [comment]
Hey, I haven't thought about this too much yet. So here are some ideas I have so far:

I’d like to keep the onboarding minimal so new users don’t get stuck for too long. Here are the pages I had in mind:

1. **Welcome page**: A quick intro to what the app is all about: exploring and tracking anime and manga.
2. **Login page**: Options for users to log in with an existing Kitsu account, create a new account, or skip the login.
3. **Basic setup**: Here, we can ask users if they want to get notified about app updates. Additionally, we could let them do some basic configuration, like choosing the app theme, the title language for anime/manga, and the poster size.

I’m not sure about the last point with the configurations. Maybe that’s already too much for the first setup.

For the design, I thought about big illustrations/images and not too much text. At the bottom, we could show the progress with little dots and add buttons for next and back for better accessibility. So both clicking or swiping to get to the next page should be possible.

Unfortunately, I don’t have much time right now, so I can’t look deeper into this. If you guys want to come up with some concepts, I’d really appreciate it!

**Comment by Drumber** [comment]
Onboarding added in [v2.0.2](https://github.com/Drumber/Kitsune/releases/tag/v2.0.2)

**Comment by RokeJulianLockhart** [comment]
This also occurs on the first launch after an/the update. Is this desirable?

**Comment by Drumber** [comment]
@RokeJulianLockhart yes, this is the expected behavior. Once the onboarding has been completed, a flag will be set, so it won't show up after future updates.
