### ISSUE TITLE
Un-uninstallable

### ISSUE THREAD

**Issue by Minzir** [Drumber/Kitsune#54]
### Problem description

I cannot uninstall this application at all.
I tried home screen uninstall. Does nothing.
App manager. Crashes.
F droid. Stalls.

I'm using galaxy note 20 5g (SM-N981B/DS)
Android 13 stock firmware

### Steps to reproduce

Just try to uninstall

### App version

1.10.7

### Android version

13

### Device information

Galaxy Note 20 5G (SM-N981B/DS)

### Acknowledgements

- [X] I have searched the open and closed [issues](https://github.com/Drumber/Kitsune/issues?q=is%3Aissue) and this is **NOT** a duplicate.
- [X] I'm using the latest version of the app.
- [X] I have provided all required information.

**Comment by Drumber** [comment]
There is not much I can do from my side as the installation and uninstallation of applications is managed by the system package manager. Though I can try to give some advice here.

You could try to clear the app data in the app info. You can access the app info page by long-clicking the app icon or from the system settings. On the same page you can also force stop the app.

If that doesn't help either, maybe a simple restart of the phone helps.

As last resort, you could try to uninstall the app with ADB from your computer. For this you need to install ADB on a computer and enable the developer settings on your phone.
1. Install ADB on your computer. You can find the android platform tools [here](https://developer.android.com/tools/releases/platform-tools)
2. Enable developer options and USB debugging on your phone (see [here](https://developer.android.com/studio/debug/dev-options) for instructions)
3. Connect your phone to your computer via USB
4. Start a terminal in the same folder where the `adb` executable file is located you've downloaded in step 1
5. Run `adb uninstall io.github.drumber.kitsune`

I don't really recommend the last option as it requires some technical knowledge.
