### ISSUE TITLE
account login 

### ISSUE THREAD

**Issue by Annepaj** [Drumber/Kitsune#56]
Am new to the app, and I don't have an kitsu account. Tried opening one but the site was unavailable. Apparently the app won't work without an account it seems. What can I do?

I couldn't comprehend git hub either. Apologies if I requested in the wrong space

**Comment by Drumber** [comment]
Hi, the owner of Kitsu.io unfortunately had to change the domain unexpectedly. Therefore, the app is currently not working.

The new domain is [kitsu.app](https://kitsu.app). You can create a new account there.
I will release a hot fix soon to make the app work with the new domain.

Related issue: #58

**Comment by Drumber** [comment]
Fixed in v2.0.1

Please update to the latest app release from [here](https://github.com/Drumber/Kitsune/releases/tag/v2.0.1).
