### ISSUE TITLE
App not working due to a domain change of Kitsu.io

### ISSUE THREAD

**Issue by Drumber** [Drumber/Kitsune#58]
**Information:**
Due to an unexpected domain change from Kitsu.io to Kitsu.app, the app is unable to retrieve new data from the API. A hot fix with the updated Kitsu domain will be released soon.

Official statement: https://kitsu.app/posts/9837041
Pull request: #57

**Comment by Drumber** [comment]
**Fixed**

The app uses now the kitsu.app domain in v2.0.1

Please update the app to the latest release.

**Comment by kaosine** [comment]
How long before it hits fdroid? That's what I'm waiting on to update it myself

**Comment by Drumber** [comment]
> How long before it hits fdroid? That's what I'm waiting on to update it myself

It can take up to 6 days until the release is available on F-Droid.

If you don't want to wait, you can install the apk from GitHub. The F-Droid and GitHub builds are signed with the same certificate, so you can install the app from both sources without re-installing/losing data.

**Comment by Drumber** [comment]
The update is now available on F-Droid.

Also, the old domain (kitsu.io) is back online. So this issue can be closed.
