### ISSUE TITLE
Update compileSdk & targetSdkVersion 34 to 35

### ISSUE THREAD

**Issue by ZineeEddine** [Drumber/Kitsune#61]
### Description

Currently, the project's **targetSdkVersion** is set to _34_. It is necessary to update it to _35_ to remain compatible with the latest versions of Android and the new Play Store requirements. This update will also bring the latest optimizations and security features.

It is important to thoroughly **test** the application **after** this update to detect possible **_regressions_** and to ensure that all **_features are working properly_**.

- https://developer.android.com/about/versions/15/get?hl=fr
- https://developer.android.com/about/versions/15/setup-sdk?hl=fr

Changes should be made in the file: build.gradle.kts (Module:app)
- https://github.com/Drumber/Kitsune/blob/master/app/build.gradle.kts
```gradle
namespace = "io.github.drumber.kitsune"
    compileSdk = 34
    buildToolsVersion = "34.0.0"

    defaultConfig {
        applicationId = "io.github.drumber.kitsune"
        minSdk = 26
        targetSdk = 34
        versionCode = 33
        versionName = "2.0.1"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"

        buildConfigField("boolean", "SCREENSHOT_MODE_ENABLED", screenshotMode)
    }
```

### Acknowledgements

- [X] I have searched the open and closed [issues](https://github.com/Drumber/Kitsune/issues?q=is%3Aissue) and this is **NOT** a duplicate.

**Comment by Drumber** [comment]
The latest release ([v2.0.2](https://github.com/Drumber/Kitsune/releases/tag/v2.0.2)) now targets SDK 35.
